export const GET_ALL_MEMBER_REQUEST = 'GET_ALL_MEMBER_REQUEST';
export const GET_ALL_MEMBER_SUCCESS = 'GET_ALL_MEMBER_SUCCESS';
export const GET_ALL_MEMBER_FAILURE = 'GET_ALL_MEMBER_FAILURE';
export const STATUS = '5f241c8c8f985b3c51e05d39cf030f4c';

export const CREATE_MEMBER_REQUEST = 'CREATE_MEMBER_REQUEST';
export const CREATE__MEMBER_FAILURE = "CREATE__MEMBER_FAILURE";
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";

// export const UPDATE_MEMBER_REQUEST = 'UPDATE_MEMBER_REQUEST';
// export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';
// export const UPDATE_MEMBER_FAILURE = 'UPDATE_MEMBER_FAILURE';

// export const GET_MEMBER = "GET_MEMBER";
// export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
// export const GET_MEMBER_FAILURE = "GET_MEMBER_FAILURE";


// export const GET_ONE_MEMBER_REQUEST = 'GET_ONE_MEMBER_REQUEST';
// export const GET_ONE_MEMBER_SUCCESS = 'GET_ONE_MEMBER_SUCCESS';
// export const GET_ONE_MEMBER_FAIL